# railway.toml

# Build commands and settings
[build]
# Build commands define how your application is built and dependencies are installed.
# These commands may vary based on your project structure and requirements.
# Replace these commands with the ones suitable for your project.
command = "python -m pip install -r requirements.txt"

# Run commands and settings
[run]
# The command to start your Flask app using Gunicorn.
# Replace 'wsgi:create' with your actual application entry point if it's different.
command = "gunicorn -w 4 -b 0.0.0.0:$PORT wsgi:create"

[env]
FLASK_ENV = "production"
SQLALCHEMY_DATABASE_URI = postgresql://postgres:freezie123@localhost:5432/ecommerce
SECRET_KEY = d9243273c065f5a1bcf6799580cc940c038f61056b83a1272c2fb9236b73

# Port configuration
# Railway sets the PORT environment variable, which should be used to bind your app.
# This line ensures your app listens on the correct port.
[deploy]
port = "${PORT}"

